// pages/about.vue
<template lang="pug">
	div
		h1.text-center Hello, My Name is Wayne Boka

		img.rounded-full.shadow-xl.mx-auto(src="/images/wb-profile250.jpg")

		p Hello! My name is Wayne and I am a website developer based out of Westfield, PA. I have been building websites and web applications since 2011.
			|
			|
			a(href="https://m.me/bokasolutions") Send me a Facebook message
			|
			| or
			|
			a(href="mailto:wayne@bokasolutions.com") email me
			|
			| to discuss how I can help build your online presence.

		h2 Skills and Interests

		.flex.flex-wrap
			.w-full(class="sm:w-1/2")
				h3 Languages

				ul
					li HTML5
					li CSS3
					li JavaScript
					li ColdFusion / Lucee
					li Python
					li Oracle
					li MySQL
			.w-full(class="sm:w-1/2")
				h3 Libraries

				ul
					li Django
					li jQuery
					li Vue
					li Bootstrap
</template>

// src/pages/about.jsx
import React from "react";
import Layout from "../components/layout";
import Bio from "../components/bio";

export default () => (
  <Layout>
    <h2 className="text-center">Hello, I'm Wayne!</h2>

    <Bio />

    <h2>Skills and Interests</h2>

    <h3>Languages</h3>

    <ul>
      <li>HTML5</li>
      <li>CSS3</li>
      <li>JavaScript</li>
      <li>ColdFusion / Lucee</li>
      <li>Python</li>
      <li>Oracle</li>
      <li>MySQL</li>
    </ul>

    <h3>Libraries</h3>

    <ul>
      <li>Django</li>
      <li>jQuery</li>
      <li>Vue</li>
      <li>Bootstrap</li>
    </ul>
  </Layout>
);
